name: tless_detector
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=11.8
  - pip
  - pip:
    - huggingface_hub
    - onnx>=1.14
    - onnxruntime-gpu
    - onnxsim
    - pycocotools
    - opencv-python
    - matplotlib
    - tqdm
    - scipy
    - trimesh
